#config.yaml
flows:
  - kolamtambaksiklus/kolam/*
excludeTags:
  - AT15
  - AT16
  - AT17
  - AT18
  - prerequisite

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - full-crud-kolam
