#config.yaml
includeTags:
  - AT11
  - AT12
  - AT13
  - AT14
  - AT15
  - AT16
  - AT17
  - AT18
  - AT19
  - AT20
  - AT21
  - AT22
excludeTags:
  - AT2
  - AT3
  - AT5
  - AT9
  - AT10
  - prerequisite
  - login
  - crud_siklus_full
  - crud_kolam_full
executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT11
        - AT12
        - AT13
        - AT14
        - AT15
        - AT16
        - AT17
        - AT18
        - AT19
        - AT20
        - AT21
        - AT22
