#config.yaml ini
flows:
  - "**"
executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT11
        - AT12
        - AT13
        - AT14
        - AT15
        - AT16
        - AT17
        - AT18
        - AT19
        - AT20
        - AT21
        - AT22
