#config.yaml
flows:
  - kolamtambaksiklus/tambak/*
excludeTags:
  - AT2
  - AT3
  - AT5
  - AT9
  - AT10
  - AT11
  - AT12
  - AT13
  - AT14
  - login

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - full-crud-tambak
